language: csharp
mono: none
dotnet: 3.1.401
addons:
    apt:
        packages:
            - powershell
            - fpc
os:
    - linux
    - osx
dist: xenial

before_install:
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install dotnetcore-sdk; fi

before_script:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cask install powershell; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install fpc; fi
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install pwsh; fi
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install freepascal; fi
    # Path refresh command based on https://travis-ci.community/t/windows-builds-refreshenv-command-not-found/5803/5
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then eval $(powershell -NonInteractive -Command 'write("export PATH=`"" + ([Environment]::GetEnvironmentVariable("PATH","Machine") + ";" + [Environment]::GetEnvironmentVariable("PATH","User")).replace("\","/").replace("C:","/c").replace(";",":") + ":`$PATH`"")'); fi

stages:
    - analyze
    - publish

jobs:
    include:
        -   stage: analyze
            script:
                - pwsh -Command "./script/travis-ci-test.ps1 -StableKey build-${TRAVIS_BUILD_NUMBER}-${TRAVIS_OS_NAME}-stable -Bucket (ConvertTo-SecureString -AsPlainText -Force -String ${THISDB_BUCKET}) -ApiKey (ConvertTo-SecureString -AsPlainText -Force -String ${THISDB_API_KEY})"
        -   stage: publish
            script:
                - pwsh -Command "./script/travis-ci-check-stable.ps1 -StableKey build-${TRAVIS_BUILD_NUMBER}-${TRAVIS_OS_NAME}-stable -Bucket (ConvertTo-SecureString -AsPlainText -Force -String ${THISDB_BUCKET}) -ApiKey (ConvertTo-SecureString -AsPlainText -Force -String ${THISDB_API_KEY})"
