language: csharp

os:
    - windows
    - linux
    - osx

mono: none
dotnet: 3.1.401

os:
    - linux
    - osx
    - windows

addons:
    apt:
        packages:
            - powershell

before_install:
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install dotnetcore-sdk; fi

before_script:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cask install powershell; fi

script:
    - dotnet test
    - pwsh script/check-eol.ps1
