name: development-test
on : [push]
defaults:
  run:
    shell: pwsh

jobs:
  development-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Test stability for development
        run: ./script/github-actions-development-test.ps1
