name: development-test
on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]
defaults:
  run:
    shell: pwsh
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-11.0]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-fpc
      - name: Test package stability
        env:
          Work_Connor_Delphi_CodeWriter_Tests_SkipDcc64: 1
        run: ./script/github-actions-test.ps1
