name: development-test
on : [push]
defaults:
  run:
    shell: pwsh

jobs:
  development-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install FPC 3.2.0
        shell: bash
        run: |
          curl -LO http://launchpadlibrarian.net/494661083/fp-units-rtl-3.2.0_3.2.0+dfsg-8build2_amd64.deb
          sudo dpkg -i fp-units-rtl-3.2.0_3.2.0+dfsg-8build2_amd64.deb
          curl -LO http://launchpadlibrarian.net/494661053/fp-compiler-3.2.0_3.2.0+dfsg-8build2_amd64.deb
          sudo dpkg -i fp-compiler-3.2.0_3.2.0+dfsg-8build2_amd64.deb
      - uses: actions/checkout@v2
      - name: Test stability for development
        run: ./script/github-actions-development-test.ps1
        env:
          Work_Connor_Delphi_CodeWriter_Tests_SkipDcc64: 1
