name: development-test
on : [push]
defaults:
  run:
    shell: pwsh

jobs:
  development-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check expected end-of-line types in text files
        run: ./script/check-eol.ps1
