name: publish
on:
  push:
    branches: [main]
defaults:
  run:
    shell: pwsh
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-11.0]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-fpc
      - name: Test package stability
        env:
          Work_Connor_Delphi_CodeWriter_Tests_SkipDcc64: 1
        run: ./script/github-actions-test.ps1
  deploy:
    needs: test
    if: ${{ !cancelled() }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy NuGet packages
        env:
          NU_GET_ORG_API_KEY: ${{ secrets.NU_GET_ORG_API_KEY }}
        run: ./script/github-actions-deploy.ps1 -Stable:$('${{ job.status }}' -eq 'success') -NuGetOrgApiKey (ConvertTo-SecureString -AsPlainText -Force -String $env:NU_GET_ORG_API_KEY)
